require('dotenv').config();

module.exports = {
	PORT: process.env.PORT,
	FRONTEND_DEVELOPMENT_URI: process.env.FRONTEND_DEVELOPMENT_URI,
	FRONTEND_PRODUCTION_URI: process.env.FRONTEND_PRODUCTION_URI,
	MONGODB_URI: process.env.MONGODB_URI,
	STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
	JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
	CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
	SMTP_HOST: process.env.SMTP_HOST,
	SMTP_PORT: process.env.SMTP_PORT,
	SMTP_USER: process.env.SMTP_USER,
	SMTP_PASS: process.env.SMTP_PASS,
	SMTP_USERNAME: process.env.SMTP_USERNAME,
};
